version: '3.8'

services:
  studentcoursemanagement:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Database=postgres;Username=postgres;Password=12345
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: localhost
    ports:
      - "5432:5432" 

  redis:
    image: redis
    ports:
      - "6379:6379" 
